// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFormField: typeof import('./src/components/auth/AppFormField.vue')['default']
    AppHeader: typeof import('./src/components/Navigation/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AuthProvider: typeof import('./src/components/auth/AuthProvider.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ForgotPassword: typeof import('./src/components/auth/ForgotPassword.vue')['default']
    MainNav: typeof import('./src/components/Navigation/MainNav.vue')['default']
    PrimaryBtn: typeof import('./src/components/buttons/PrimaryBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./src/components/auth/SignIn.vue')['default']
    SignUp: typeof import('./src/components/auth/SignUp.vue')['default']
    TheAlerts: typeof import('./src/components/TheAlerts.vue')['default']
    ThemeToggler: typeof import('./src/components/Navigation/ThemeToggler.vue')['default']
  }
}

export {}
