// https://docs.cypress.io/api/introduction/api.html

describe('Register Test', () => {
  beforeEach(() => {
    cy.logout()
  })

  it('Register Input Validator', () => {
    cy.visit('/')
    cy.url().should('include', '/auth')
    cy.get('#authCreate').click()
    cy.get('#makeCreate').should('exist').click()
    cy.contains('Email es requerido')
    cy.contains('Contraseña es requerido')
    cy.contains('Repetir contraseña es requerido')
    cy.contains('Nombre es requerido')
    cy.contains('Apellidos es requerido')
  })
  it('Register check and signUp, redirect to dashboard and Logout', () => {
    cy.visit('/auth/showSignUp')
    cy.get('#email')
      .should('have.value', '')
      .type('cypress@test.es')
      .should('have.value', 'cypress@test.es')
    cy.get('#password')
      .should('have.value', '')
      .type('123456')
      .should('have.value', '123456')
    cy.get('#passwordCheck')
      .should('have.value', '')
      .type('123456')
      .should('have.value', '123456')
    cy.get('#name')
      .should('have.value', '')
      .type('test')
      .should('have.value', 'test')
    cy.get('#surname')
      .should('have.value', '')
      .type('test')
      .should('have.value', 'test')
    cy.get('#makeCreate').should('exist').click()
    cy.contains(
      'La dirección de correo especificada ya está siendo utilizada. Por favor, elige otra.'
    )
    cy.contains('OK').click()
    cy.get('#email').clear().type('cypress99@test.es')
    cy.get('#makeCreate').click()
    cy.url().should('include', '/')
    cy.get('#sidebarBtn').click()
    cy.get('#deleteUser').click()
    cy.get('.swal2-confirm').click()
    //wait 3 sec
    cy.wait(3000)
    cy.url().should('include', '/auth')
    cy.contains('Deleted!')
  })
})
